from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from lspp_mcp.templates import render_template  # noqa: E402


class TemplateTests(unittest.TestCase):
    def test_d3plot_template_renders_expected_commands(self) -> None:
        rendered = render_template(
            "export_d3plot_contour.cfile.j2",
            {
                "open_command": "openc",
                "d3plot_path": "D:/case/d3plot",
                "fringe_code": 9,
                "state_index": 3,
                "view_command": "isometric x",
                "part_command": "m 1,2,3",
                "show_legend": 1,
                "show_triad": 0,
                "background_rgb": "1 1 1",
                "title_command": "title 0",
                "range_level_commands": "range level 50\nrange pal update",
                "image_format": "png",
                "print_format": "png",
                "output_image": "D:/case/post/out.png",
            },
        )
        self.assertIn('openc d3plot "D:/case/d3plot"', rendered)
        self.assertIn("fringe 9", rendered)
        self.assertIn("pfringe", rendered)
        self.assertIn("state 3", rendered)
        self.assertIn("range level 50", rendered)
        self.assertIn("range pal update", rendered)
        self.assertIn('print png "D:/case/post/out.png" opaque enlisted "OGL1x1"', rendered)
        self.assertTrue(rendered.startswith("c generated by lspp-mcp-server"))
        self.assertTrue(rendered.rstrip().endswith("exit"))

    def test_d3plot_template_renders_non_png_format(self) -> None:
        rendered = render_template(
            "export_d3plot_contour.cfile.j2",
            {
                "open_command": "openc",
                "d3plot_path": "D:/case/d3plot",
                "fringe_code": 9,
                "state_index": 3,
                "view_command": "front",
                "part_command": "pall",
                "show_legend": 1,
                "show_triad": 0,
                "background_rgb": "1 1 1",
                "title_command": "title 0",
                "range_level_commands": "",
                "image_format": "wrl",
                "print_format": "vrml",
                "output_image": "D:/case/post/out.wrl",
            },
        )
        self.assertIn('print vrml "D:/case/post/out.wrl" opaque enlisted "OGL1x1"', rendered)

    def test_ascii_template_renders_nodout(self) -> None:
        rendered = render_template(
            "extract_ascii_curve.cfile.j2",
            {
                "ascii_type": "nodout",
                "file_path": "D:/case/nodout",
                "plot_expression": "1 1001",
                "xyplot_window": 1,
                "output_csv": "D:/case/post/node.csv",
            },
        )
        self.assertIn('ascii nodout open "D:/case/nodout" 0', rendered)
        self.assertIn("ascii nodout plot 1 1001", rendered)
        self.assertIn('xyplot 1 savefile ms_csv "D:/case/post/node.csv" 1 all', rendered)
        self.assertIn("deletewin 1", rendered)

    def test_binout_template_renders_plot_command(self) -> None:
        rendered = render_template(
            "extract_binout_curve.cfile.j2",
            {
                "mpp_note": "c SMP binout input",
                "binout_path": "D:/case/binout",
                "block": "glstat",
                "index1": 0,
                "index2": 1,
                "entity_index": 0,
                "binout_variable": "kinetic_energy",
                "xyplot_window": 1,
                "output_csv": "D:/case/post/ke.csv",
            },
        )
        self.assertIn('binaski load "D:/case/binout"', rendered)
        self.assertIn(
            'binaski plot "D:/case/binout" glstat 0 1 0 kinetic_energy ;',
            rendered,
        )

    def test_node_history_template_renders_genselect(self) -> None:
        rendered = render_template(
            "extract_d3plot_node_history.cfile.j2",
            {
                "open_command": "openc",
                "d3plot_path": "D:/case/d3plot",
                "node_id": 1001,
                "variable_code": 4,
                "xyplot_window": 1,
                "output_csv": "D:/case/post/node.csv",
            },
        )
        self.assertIn("genselect target node", rendered)
        self.assertIn("genselect node add node 1001/0", rendered)
        self.assertIn("ntime 4", rendered)


if __name__ == "__main__":
    unittest.main()
